#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

# Add Node.js to PATH for GitHub Desktop
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

npm run lint:fix && npm run format:write && git add .
